<!-- invify-admin/src/pages/tenant/TenantSettingsPage.vue -->
<template>
  <q-page class="q-pa-lg text-white" style="background: #05070d; min-height: 100vh;">
    
    <!-- Top Header -->
    <div class="row items-center justify-between q-mb-xl">
      <div>
        <div class="row items-center op-gap-8 no-wrap">
          <q-icon name="tune" color="grey-4" size="md" />
          <h1 class="text-h4 text-weight-bolder text-white q-my-none letter-spacing-1">Portal Settings</h1>
        </div>
        <div class="text-caption text-grey-5 q-mt-xs">
          Manage business modules, customize invoice branding, audit subscription plans, and configure API key channels.
        </div>
      </div>
      
      <q-btn unelevated color="indigo-10" icon="save" label="Apply Preferences" @click="savePreferences" class="text-weight-bold text-caption" />
    </div>

    <!-- 1. Industry Module Orchestration -->
    <div class="row q-col-gutter-lg q-mb-lg">
      
      <!-- Module Selector -->
      <div class="col-12 col-lg-8">
        <q-card class="bg-card-dark border-grey-9 q-pa-lg fit">
          <div class="text-h6 text-weight-bold text-white q-mb-xs">Dynamic Module Provisioning Matrix</div>
          <div class="text-caption text-grey-5 q-mb-md">Workspace operational module provisioned for this tenant. Contact Super Admin to switch mode.</div>

          <!-- Active Module — prominently displayed -->
          <div
            v-for="mod in modules.filter(m => m.id === activeModule)"
            :key="mod.id"
            class="q-pa-md rounded-borders row items-center justify-between q-mb-md active-module"
          >
            <div class="row items-center op-gap-12 col">
              <q-icon :name="mod.icon" :color="mod.color" size="sm" />
              <div class="col">
                <div class="text-caption text-weight-bold text-white">{{ mod.name }}</div>
                <div class="text-caption text-grey-5" style="font-size: 11px;">{{ mod.desc }}</div>
                <!-- School-specific feature chips -->
                <div class="row q-gutter-x-xs q-mt-xs" v-if="mod.id === 'school'">
                  <q-chip dense size="xs" color="indigo-10" text-color="indigo-3" icon="menu_book">Curriculum Tools</q-chip>
                  <q-chip dense size="xs" color="indigo-10" text-color="indigo-3" icon="assignment">Lesson Report Cards</q-chip>
                  <q-chip dense size="xs" color="indigo-10" text-color="indigo-3" icon="people">Student Attendance</q-chip>
                  <q-chip dense size="xs" color="indigo-10" text-color="indigo-3" icon="payments">Tuition Fee Matrix</q-chip>
                </div>
              </div>
            </div>
            <div class="row items-center op-gap-8">
              <q-badge color="green-10" text-color="green-3" class="text-metric-sm text-weight-bold q-px-sm">
                <q-icon name="check_circle" size="xs" class="q-mr-xs" />ACTIVE PREFERENCE
              </q-badge>
            </div>
          </div>

          <!-- Collapsed: other modules (hidden by default) -->
          <q-expansion-item
            dense
            dark
            icon="visibility_off"
            label="Other Available Modules (Not Provisioned)"
            header-class="text-grey-6 text-caption q-pa-none"
            expand-icon-class="text-grey-7"
            class="q-mt-xs"
          >
            <div class="column q-gutter-y-sm q-mt-sm">
              <div
                v-for="mod in modules.filter(m => m.id !== activeModule)"
                :key="mod.id"
                class="q-pa-sm rounded-borders row items-center justify-between bg-black-transparent opacity-40"
                style="border: 1px solid rgba(255,255,255,0.04);"
              >
                <div class="row items-center op-gap-8 col">
                  <q-icon :name="mod.icon" color="grey-8" size="xs" />
                  <div class="col">
                    <div class="text-caption text-grey-7">{{ mod.name }}</div>
                    <div class="text-grey-8" style="font-size: 10px;">{{ mod.desc }}</div>
                  </div>
                </div>
                <q-badge color="grey-9" text-color="grey-6" class="text-metric-sm" size="xs">NOT PROVISIONED</q-badge>
              </div>
            </div>
          </q-expansion-item>
        </q-card>
      </div>

      <!-- Receipt & Brand Customization -->
      <div class="col-12 col-lg-4">
        <q-card class="bg-card-dark border-grey-9 q-pa-lg fit column justify-between">
          <div>
            <div class="text-h6 text-weight-bold text-white q-mb-xs">Receipt & Invoice Branding</div>
            <div class="text-caption text-grey-5 q-mb-md">Customize receipt layouts generated by terminal checkouts.</div>

            <div class="column q-gutter-y-md">
              <q-input v-model="branding.tagline" dark outlined dense label="Corporate Tagline" placeholder="e.g. Quality education for all" />
              <q-input v-model="branding.hex" dark outlined dense label="Primary Brand Color (Hex)" placeholder="#4f46e5" class="font-mono text-caption" />
              <q-input v-model="branding.receiptFootnote" dark outlined dense autogrow label="Receipt Footnote Details" placeholder="Thank you for your patronage! Replay audit node verified." />
            </div>
          </div>

          <!-- Preview box -->
          <div class="q-pa-md rounded-borders border-grey-9 bg-black-transparent q-mt-md">
            <div class="text-metric-mono font-mono text-uppercase text-grey-5 q-mb-xs" style="font-size: 9px; letter-spacing: 1px;">Brand Palette Preview</div>
            <div class="row items-center op-gap-8">
              <div class="rounded-borders" :style="`width: 24px; height: 24px; background: ${branding.hex || '#6366f1'};`" />
              <span class="text-caption font-mono text-weight-bold text-white">{{ branding.hex || '#6366f1' }}</span>
            </div>
          </div>
        </q-card>
      </div>

    </div>

    <!-- 2. Subscription, Quota & API Credentials -->
    <div class="row q-col-gutter-lg">
      
      <!-- Plan & Limits Summary -->
      <div class="col-12 col-md-6">
        <q-card class="bg-card-dark border-grey-9 q-pa-lg fit">
          <div class="row items-center justify-between q-mb-md">
            <div>
              <div class="text-h6 text-weight-bold text-white">Quotas & Subscription Limits</div>
              <div class="text-caption text-grey-5">Plan features scoped to your active subscription.</div>
            </div>
            <q-badge color="purple-10" text-color="purple-3" class="text-metric-sm text-weight-bold q-px-md q-py-xs" style="font-size: 11px;">ENTERPRISE PLAN</q-badge>
          </div>

          <q-list separator class="border-grey-9 rounded-borders">
            <q-item class="q-py-md" v-for="quota in quotas" :key="quota.name">
              <q-item-section>
                <q-item-label class="text-weight-bold text-white">{{ quota.name }}</q-item-label>
                <q-item-label caption class="text-grey-5">{{ quota.desc }}</q-item-label>
              </q-item-section>
              <q-item-section side class="text-right">
                <div class="text-metric-mono font-mono text-weight-bold text-white" style="font-size: 12.5px;">{{ quota.usage }} / {{ quota.limit }}</div>
                <div class="w-full q-mt-xs" style="width: 100px;">
                  <q-linear-progress :value="quota.val" color="purple-4" dark class="rounded-borders" />
                </div>
              </q-item-section>
            </q-item>
          </q-list>
        </q-card>
      </div>

      <!-- API Credentials Manager -->
      <div class="col-12 col-md-6">
        <q-card class="bg-card-dark border-grey-9 q-pa-lg fit column justify-between">
          <div>
            <div class="row items-center justify-between q-mb-xs">
              <div class="text-h6 text-weight-bold text-white">API Credentials Infrastructure</div>
              <q-badge
                :color="apiKey ? 'green-8' : 'amber-8'"
                :label="apiKey ? 'PROVISIONED' : 'NOT PROVISIONED'"
                class="text-weight-bold text-caption"
              />
            </div>
            <div class="text-caption text-grey-5 q-mb-md">Connect external inventory systems or ERP databases safely. Public key only — secrets are vault-protected.</div>

            <!-- Public API Key field -->
            <q-input
              v-model="apiKey"
              dark outlined dense readonly
              :label="apiKey ? 'Active Public API Key (pk_test_…)' : 'Public API Key'"
              :placeholder="apiKey ? '' : 'Not yet provisioned — activate Financial Platform first'"
              class="font-mono text-caption q-mb-md"
            >
              <template v-slot:prepend v-if="!apiKey">
                <q-icon name="lock_open" color="amber-5" size="xs" />
              </template>
              <template v-slot:prepend v-if="apiKey">
                <q-icon name="verified_user" color="green-4" size="xs" />
              </template>
              <template v-slot:append v-if="apiKey">
                <q-btn flat dense color="indigo-4" icon="content_copy" @click="copyKey" />
              </template>
            </q-input>

            <q-input
              v-model="webhookUrl"
              dark outlined dense
              label="Your Webhook Notification Endpoint URL"
              placeholder="e.g. https://yourdomain.com/api/v1/quasar-webhook"
              class="font-mono text-caption"
            />
          </div>

          <q-btn outline color="indigo-4" label="Regenerate API Credentials" @click="regenKey" class="full-width q-mt-md text-weight-bold letter-spacing-1" />
        </q-card>
      </div>

    </div>

  </q-page>
</template>

<script setup>
import { onMounted } from 'vue';
import { useQuasar } from 'quasar';
import { useTenantSettingStore } from '../stores/tenantSettingStore';
import { storeToRefs } from 'pinia';

const $q = useQuasar();
const store = useTenantSettingStore();

const { activeModule, branding, apiKey, webhookUrl, modules, quotas } = storeToRefs(store);

const savePreferences = () => {
  const msg = store.savePreferences();
  $q.notify({
    type: 'positive',
    message: msg
  });
  
  setTimeout(() => {
    window.location.reload()
  }, 1000)
}

const copyKey = () => {
  navigator.clipboard?.writeText(apiKey.value).catch(() => {
    const el = document.createElement('textarea');
    el.value = apiKey.value;
    document.body.appendChild(el);
    el.select();
    document.execCommand('copy');
    document.body.removeChild(el);
  });
  $q.notify({ type: 'positive', message: 'Public API key copied to clipboard.' });
}

const regenKey = () => {
  $q.dialog({
    title: 'Regenerate API Client Credentials?',
    message: 'Any existing inventory integrations mapping to the current client secret key will instantly drop and return 401 Unauthorized errors until updated. Confirm regeneration?',
    cancel: true,
    dark: true
  }).onOk(async () => {
    try {
      await store.regenerateKey();
      $q.notify({ type: 'positive', message: 'New cryptographically strong client credentials minted.' });
    } catch (e) {
      $q.notify({
        type: 'negative',
        message: e?.response?.data?.error || e?.message || 'Failed to regenerate credentials'
      });
    }
  })
}

onMounted(() => {
  store.loadBrandingPrefs();
})
</script>

<style scoped>
.border-grey-9 { border: 1px solid rgba(255,255,255,0.06); }
.bg-card-dark { background: #0b0f19; }
.bg-black-transparent { background: rgba(0, 0, 0, 0.25) !important; }
.letter-spacing-1 { letter-spacing: 1px; }

.active-module {
  background: linear-gradient(135deg, rgba(79, 70, 229, 0.15) 0%, rgba(255,255,255,0.01) 100%) !important;
  border: 1px solid rgba(99, 102, 241, 0.3) !important;
}

.transition-3 { transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1); }
.font-mono { font-family: 'Courier New', Courier, monospace; }
</style>
