// src/services/invite.service.ts
import crypto from 'crypto';
import { supabase } from '../db/supabase';

export class InviteService {
  /**
   * Generates a secure invitation with a hashed token.
   * Senior Policy: Invitations are strictly for 'staff' role only.
   */
  static async createInvite(tenantId: string, email: string) {
    try {
      const role = 'staff'; // Enforced: No tenant_admin invites via this flow.

      // 1. Check for existing pending invite
      const { data: existing } = await supabase
        .from('invites')
        .select('*')
        .eq('tenant_id', tenantId)
        .eq('email', email)
        .eq('status', 'pending')
        .gte('expires_at', new Date().toISOString())
        .single();

      if (existing) {
        return { invite: existing, rawToken: null, isNew: false };
      }

      // 2. Generate secure random token (32 bytes as requested)
      const rawToken = crypto.randomBytes(32).toString('hex');
      const tokenHash = this.hashToken(rawToken);
      const expiresAt = new Date();
      expiresAt.setHours(expiresAt.getHours() + 48); // 48 hour expiry

      // 3. Store hashed token
      const { data: invite, error } = await supabase
        .from('invites')
        .insert({
          tenant_id: tenantId,
          email,
          role,
          token_hash: tokenHash,
          expires_at: expiresAt.toISOString(),
          status: 'pending'
        })
        .select()
        .single();

      if (error) throw error;

      return { invite, rawToken, isNew: true };
    } catch (error: any) {
      console.error('[InviteService] createInvite Error:', error.message);
      throw error;
    }
  }

  /**
   * Validates a raw token against its stored hash.
   */
  static async validateToken(rawToken: string) {
    const tokenHash = this.hashToken(rawToken);
    
    const { data: invite, error } = await supabase
      .from('invites')
      .select('*, tenants(name, quaser_api_key)') // quaser_api_key just for context, usually logo would be in metadata
      .eq('token_hash', tokenHash)
      .eq('status', 'pending')
      .gte('expires_at', new Date().toISOString())
      .single();

    if (error || !invite) {
      throw new Error('Invalid or expired invitation token');
    }

    return invite;
  }

  /**
   * Hashes the token using SHA256.
   */
  private static hashToken(token: string): string {
    return crypto.createHash('sha256').update(token).digest('hex');
  }
}

/**
 * Mock Service for Email Notifications during local development.
 */
export class NotificationService {
  static async sendInviteEmail(email: string, schoolName: string, inviteLink: string) {
    console.log(`
      ╔════════════════════════════════════════════════════════════════════╗
      ║  [INVIFY NOTIFICATION]                                             ║
      ╚════════════════════════════════════════════════════════════════════╝
      To: ${email}
      Subject: Action Required: You're invited to join ${schoolName}
      
      Hello,
      
      You have been invited as a Staff Member to join the digital 
      workspace of ${schoolName} on Invify.
      
      Invify helps you generate NERDC-compliant lesson notes and 
      collaborate with your colleagues in seconds.
      
      ──────────────────────────────────────────────────────────────────────
      [ ACCEPT INVITATION ]
      ${inviteLink}
      ──────────────────────────────────────────────────────────────────────
      
      If the button above doesn't work, copy and paste the URL into 
      your browser. This link will expire in 48 hours for your security.
      
      Best Regards,
      The Invify Team
      ----------------------------------------------------------------------
      Generated by Invify | Empowering Nigerian Educators
    `);
  }

  static async sendQuotaWarning(tenantId: string, usage: number, limit: number) {
    // 1. Fetch Tenant Owner
    const { data: user } = await supabase.from('users').select('email, tenants(name)').eq('tenant_id', tenantId).eq('role', 'owner').single();
    if (!user) return;

    console.log(`
      ╔════════════════════════════════════════════════════════════════════╗
      ║  [INVIFY QUOTA ALERT]                                              ║
      ╚════════════════════════════════════════════════════════════════════╝
      To: ${user.email}
      Subject: Action Required: Your AI Generation limit is almost full
      
      Hello ${(user as any).tenants?.name},
      
      Your school has generated ${usage} lesson notes this month. 
      You have used over 90% of your current plan quota (${limit}).
      
      To ensure your teachers can continue generating notes without 
      interruption, we recommend upgrading to the Basic or Premium plan.
      
      ──────────────────────────────────────────────────────────────────────
      [ UPGRADE MY PLAN ]
      ${process.env.APP_URL || 'http://localhost:9000'}/#/admin/billing
      ──────────────────────────────────────────────────────────────────────
      
      Best Regards,
      The Invify Growth Team
    `);
  }
}
