<!-- invify-admin/src/pages/tenant/TenantSettingsPage.vue -->
<template>
  <q-page class="q-pa-lg text-white" style="background: #05070d; min-height: 100vh;">
    
    <!-- Top Header -->
    <div class="row items-center justify-between q-mb-xl">
      <div>
        <div class="row items-center op-gap-8 no-wrap">
          <q-icon name="tune" color="grey-4" size="md" />
          <h1 class="text-h4 text-weight-bolder text-white q-my-none letter-spacing-1">Portal Settings</h1>
        </div>
        <div class="text-caption text-grey-5 q-mt-xs">
          Manage business modules, customize invoice branding, audit subscription plans, and configure API key channels.
        </div>
      </div>
      
      <q-btn unelevated color="indigo-10" icon="save" label="Apply Preferences" @click="savePreferences" class="text-weight-bold text-caption" />
    </div>

    <!-- 1. Industry Module Orchestration -->
    <div class="row q-col-gutter-lg q-mb-lg">
      
      <!-- Module Selector -->
      <div class="col-12 col-lg-8">
        <q-card class="bg-card-dark border-grey-9 q-pa-lg fit">
          <div class="text-h6 text-weight-bold text-white q-mb-xs">Dynamic Module Provisioning Matrix</div>
          <div class="text-caption text-grey-5 q-mb-md">Toggle authoritative capabilities in real-time. Toggles will instantly modify the active sidebar workspace layout.</div>

          <div class="column q-gutter-y-sm">
            <div 
              v-for="mod in modules" 
              :key="mod.id" 
              class="q-pa-md rounded-borders border-grey-9 row items-center justify-between transition-3"
              :class="activeModule === mod.id ? 'active-module' : 'bg-black-transparent'"
              @click="switchModule(mod.id)"
            >
              <div class="row items-center op-gap-12 col">
                <q-icon :name="mod.icon" :color="activeModule === mod.id ? mod.color : 'grey-5'" size="sm" />
                <div class="col">
                  <div class="text-caption text-weight-bold text-white">{{ mod.name }}</div>
                  <div class="text-caption text-grey-5" style="font-size: 11px;">{{ mod.desc }}</div>
                </div>
              </div>
              <div class="row items-center op-gap-8">
                <q-badge color="indigo-10" text-color="indigo-3" class="text-metric-sm text-weight-bold" v-if="activeModule === mod.id">ACTIVE PREFERENCE</q-badge>
                <q-radio v-model="activeModule" :val="mod.id" dark color="indigo-4" />
              </div>
            </div>
          </div>
        </q-card>
      </div>

      <!-- Receipt & Brand Customization -->
      <div class="col-12 col-lg-4">
        <q-card class="bg-card-dark border-grey-9 q-pa-lg fit column justify-between">
          <div>
            <div class="text-h6 text-weight-bold text-white q-mb-xs">Receipt & Invoice Branding</div>
            <div class="text-caption text-grey-5 q-mb-md">Customize receipt layouts generated by terminal checkouts.</div>

            <div class="column q-gutter-y-md">
              <q-input v-model="branding.tagline" dark outlined dense label="Corporate Tagline" placeholder="e.g. Quality education for all" />
              <q-input v-model="branding.hex" dark outlined dense label="Primary Brand Color (Hex)" placeholder="#4f46e5" class="font-mono text-caption" />
              <q-input v-model="branding.receiptFootnote" dark outlined dense autogrow label="Receipt Footnote Details" placeholder="Thank you for your patronage! Replay audit node verified." />
            </div>
          </div>

          <!-- Preview box -->
          <div class="q-pa-md rounded-borders border-grey-9 bg-black-transparent q-mt-md">
            <div class="text-metric-mono font-mono text-uppercase text-grey-5 q-mb-xs" style="font-size: 9px; letter-spacing: 1px;">Brand Palette Preview</div>
            <div class="row items-center op-gap-8">
              <div class="rounded-borders" :style="`width: 24px; height: 24px; background: ${branding.hex || '#6366f1'};`" />
              <span class="text-caption font-mono text-weight-bold text-white">{{ branding.hex || '#6366f1' }}</span>
            </div>
          </div>
        </q-card>
      </div>

    </div>

    <!-- 2. Subscription, Quota & API Credentials -->
    <div class="row q-col-gutter-lg">
      
      <!-- Plan & Limits Summary -->
      <div class="col-12 col-md-6">
        <q-card class="bg-card-dark border-grey-9 q-pa-lg fit">
          <div class="row items-center justify-between q-mb-md">
            <div>
              <div class="text-h6 text-weight-bold text-white">Quotas & Subscription Limits</div>
              <div class="text-caption text-grey-5">Plan features scoped to your active subscription.</div>
            </div>
            <q-badge color="purple-10" text-color="purple-3" class="text-metric-sm text-weight-bold q-px-md q-py-xs" style="font-size: 11px;">ENTERPRISE PLAN</q-badge>
          </div>

          <q-list separator class="border-grey-9 rounded-borders">
            <q-item class="q-py-md" v-for="quota in quotas" :key="quota.name">
              <q-item-section>
                <q-item-label class="text-weight-bold text-white">{{ quota.name }}</q-item-label>
                <q-item-label caption class="text-grey-5">{{ quota.desc }}</q-item-label>
              </q-item-section>
              <q-item-section side class="text-right">
                <div class="text-metric-mono font-mono text-weight-bold text-white" style="font-size: 12.5px;">{{ quota.usage }} / {{ quota.limit }}</div>
                <div class="w-full q-mt-xs" style="width: 100px;">
                  <q-linear-progress :value="quota.val" color="purple-4" dark class="rounded-borders" />
                </div>
              </q-item-section>
            </q-item>
          </q-list>
        </q-card>
      </div>

      <!-- API Credentials Manager -->
      <div class="col-12 col-md-6">
        <q-card class="bg-card-dark border-grey-9 q-pa-lg fit column justify-between">
          <div>
            <div class="text-h6 text-weight-bold text-white q-mb-xs">API Credentials Infrastructure</div>
            <div class="text-caption text-grey-5 q-mb-md">Connect external inventory systems or ERP databases safely.</div>

            <q-input v-model="apiKey" dark outlined dense readonly label="Active Production Client Secret Key" class="font-mono text-caption q-mb-md">
              <template v-slot:append>
                <q-btn flat dense color="indigo-4" icon="content_copy" @click="copyKey" />
              </template>
            </q-input>

            <q-input v-model="webhookUrl" dark outlined dense label="Quasar Webhook Notification Endpoint URL" class="font-mono text-caption" />
          </div>

          <q-btn outline color="indigo-4" label="Regenerate API Credentials" @click="regenKey" class="full-width q-mt-md text-weight-bold letter-spacing-1" />
        </q-card>
      </div>

    </div>

  </q-page>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { useQuasar } from 'quasar'

const $q = useQuasar()

const activeModule = ref(localStorage.getItem('tenant_type') || 'school')

const branding = ref({
  tagline: '',
  hex: '#6366f1',
  receiptFootnote: ''
})

const apiKey = ref('sk_live_invify_9281x_quasar_8802a')
const webhookUrl = ref('https://mybusiness.com/api/v1/quasar-webhook')

const modules = ref([
  { id: 'school', name: 'School & Academy Management', desc: 'Provision curriculum tools, lesson report cards, student attendance logs, and academy tuition fee matrices.', icon: 'school', color: 'indigo-4' },
  { id: 'retail', name: 'Retail & POS Stock Operations', desc: 'Provision physical point-of-sale checkout speeds, inventory matrices, depletion alerts, and customer invoices.', icon: 'point_of_sale', color: 'amber-4' },
  { id: 'hospitality', name: 'Hospitality Room & Reserve System', desc: 'Provision booking schedules, occupancy matrices, guest details registry, and service catalog billings.', icon: 'king_bed', color: 'cyan-4' },
  { id: 'logistics', name: 'Logistics Fleet & Dispatch Track', desc: 'Provision vehicle GPS pipelines, delivery analytics matrices, driver logs, and fuel ledgers.', icon: 'local_shipping', color: 'green-4' },
  { id: 'healthcare', name: 'Healthcare Clinic Patient Hub', desc: 'Provision pharmacy dispensers, appointment queues, patient charts, and clinician checklists.', icon: 'healing', color: 'red-4' }
])

const quotas = ref([
  { name: 'Active POS Operators', desc: 'Total active staff nodes created.', usage: '3', limit: '10', val: 0.3 },
  { name: 'AI Copilot Query Allocations', desc: 'Aggregated analytics insights queries remaining.', usage: '840', limit: '1,000', val: 0.84 },
  { name: 'Telemetry Storage Data', desc: 'Immutable audit transaction logs stored.', usage: '2.4 GB', limit: '10 GB', val: 0.24 }
])

const switchModule = (id) => {
  activeModule.value = id
}

const savePreferences = () => {
  localStorage.setItem('tenant_type', activeModule.value)
  $q.notify({
    type: 'positive',
    message: `Preferences applied successfully. Workspace provisions shifted to [${activeModule.value.toUpperCase()}].`
  })
  
  // Reload window briefly after small delay to hydrate layout tree cleanly!
  setTimeout(() => {
    window.location.reload()
  }, 1000)
}

const copyKey = () => {
  const el = document.createElement('textarea')
  el.value = apiKey.value
  document.body.appendChild(el)
  el.select()
  document.execCommand('copy')
  document.body.removeChild(el)
  $q.notify({ type: 'positive', message: 'API client secret copied to clipboard.' })
}

const regenKey = () => {
  $q.dialog({
    title: 'Regenerate API Client Credentials?',
    message: 'Any existing inventory integrations mapping to the current client secret key will instantly drop and return 401 Unauthorized errors until updated. Confirm regeneration?',
    cancel: true,
    dark: true
  }).onOk(() => {
    apiKey.value = 'sk_live_invify_' + Math.floor(Math.random() * 100000) + '_quasar_key'
    $q.notify({ type: 'positive', message: 'New cryptographically strong client credentials minted.' })
  })
}

onMounted(() => {
  // Read branding preferences from localStorage if exists
  const savedBranding = localStorage.getItem('tenant_branding_prefs')
  if (savedBranding) {
    try {
      branding.value = JSON.parse(savedBranding)
    } catch (e) {}
  }
})
</script>

<style scoped>
.border-grey-9 { border: 1px solid rgba(255,255,255,0.06); }
.bg-card-dark { background: #0b0f19; }
.bg-black-transparent { background: rgba(0, 0, 0, 0.25) !important; }
.letter-spacing-1 { letter-spacing: 1px; }

.active-module {
  background: linear-gradient(135deg, rgba(79, 70, 229, 0.15) 0%, rgba(255,255,255,0.01) 100%) !important;
  border: 1px solid rgba(99, 102, 241, 0.3) !important;
}

.transition-3 { transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1); }
.font-mono { font-family: 'Courier New', Courier, monospace; }
</style>
