-- ─────────────────────────────────────────────────────────────────────────────
-- P0-5E Migration: complaints, apk_vault, apk_deployment_logs, audit_log_archive
-- ─────────────────────────────────────────────────────────────────────────────
--
-- SCHEMA VERIFICATION FINDINGS (pre-migration audit, 2026-06-19)
-- ──────────────────────────────────────────────────────────────
-- Column                 | Live DB Type | Evidence
-- ─────────────────────────────────────────────────────────────
-- users.id               | UUID         | auth.uid()-compatible; p05c uses users.id = auth.uid() without cast
-- users.tenant_id        | TEXT         | p05c uses users.tenant_id::text; users_db.json stores as string
-- devices.id             | TEXT         | devices_db.json: "id": "dev-1781561032451" (custom TEXT PK)
-- devices.device_id      | TEXT         | devices_db.json: "device_id": "R52M3012KRB"
-- audit_logs.id          | UUID         | p05c migration: id UUID PRIMARY KEY DEFAULT gen_random_uuid()
-- terminal_audit_log.id  | UUID         | terminal_migration.sql: id UUID PRIMARY KEY DEFAULT gen_random_uuid()
-- tenants.id             | UUID         | Standard Supabase UUID PK on tenants table
--
-- DESIGN DECISIONS:
-- 1. complaints.device_id  → TEXT (matches devices.id TEXT primary key)
-- 2. complaints.tenant_id  → UUID REFERENCES tenants(id) (standard FK)
-- 3. audit_log_archive.original_log_id → TEXT
--      Because source tables differ:
--        - audit_logs.id         is UUID
--        - terminal_audit_log.id is UUID
--      Both are UUIDs, but to support future TEXT sources and avoid a union
--      type problem, we store as TEXT and allow the application to pass
--      either UUID or TEXT values. UUID values will be stored as their
--      canonical string representation.
-- 4. RLS: RESTRICTIVE policies block INSERT + UPDATE + DELETE for all
--      client JWT roles. SELECT is granted only where business rules allow.
--      Backend services use supabaseAdmin (service role) which bypasses RLS.
--
-- CAST PATTERN (consistent with p05b / p05c migrations):
--   users.id = auth.uid()                          ← both UUID, no cast needed
--   users.tenant_id::text = <table>.tenant_id::text ← users.tenant_id is TEXT,
--                                                      UUID column cast to text
-- ─────────────────────────────────────────────────────────────────────────────

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. complaints table
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.complaints (
    id             TEXT        PRIMARY KEY,  -- TKT-XXXXXX format generated by SupportController
    title          TEXT        NOT NULL,
    description    TEXT        NOT NULL,
    category       TEXT        NOT NULL DEFAULT 'general',
    urgency        TEXT        NOT NULL DEFAULT 'normal'
                   CHECK (urgency IN ('normal', 'high', 'critical')),
    status         TEXT        NOT NULL DEFAULT 'pending'
                   CHECK (status IN ('pending', 'in_progress', 'resolved', 'closed')),
    tenant_id      UUID        NULL REFERENCES public.tenants(id) ON DELETE SET NULL,
    tenant_code    VARCHAR(20) NULL,      -- Denormalized; populated from tenants.tenant_code by controller
    tenant_name    TEXT        NULL,      -- Denormalized display only; mutable, do not use for lookups
    -- device_id is TEXT to match public.devices.id which uses custom "dev-XXXXX" TEXT primary key
    device_id      TEXT        NULL,      -- No FK constraint: devices may be deleted; TEXT PK on devices table
    incident_date  TIMESTAMPTZ NULL,
    attachment_url TEXT        NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_complaints_tenant_id   ON public.complaints(tenant_id);
CREATE INDEX IF NOT EXISTS idx_complaints_tenant_code ON public.complaints(tenant_code);
CREATE INDEX IF NOT EXISTS idx_complaints_device_id   ON public.complaints(device_id);
CREATE INDEX IF NOT EXISTS idx_complaints_status      ON public.complaints(status);
CREATE INDEX IF NOT EXISTS idx_complaints_created_at  ON public.complaints(created_at DESC);

-- ─────────────────────────────────────────────────────────────────────────────
-- 2. apk_vault table
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.apk_vault (
    id                      TEXT        PRIMARY KEY,  -- apk-XXXXXX format
    name                    TEXT        NOT NULL,
    package_name            TEXT        NOT NULL,
    version                 TEXT        NOT NULL,
    size                    INTEGER     NOT NULL,
    status                  TEXT        NOT NULL DEFAULT 'READY',
    upload_progress         INTEGER     NOT NULL DEFAULT 100,
    install_count           INTEGER     NOT NULL DEFAULT 0,
    uninstall_count         INTEGER     NOT NULL DEFAULT 0,
    version_distribution    JSONB       NOT NULL DEFAULT '[]'::jsonb,
    selected_deploy_version TEXT        NULL,
    s3_url                  TEXT        NOT NULL,
    created_by              TEXT        NULL,
    updated_by              TEXT        NULL,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Unique constraint: one record per package_name (enforces APK identity)
CREATE UNIQUE INDEX IF NOT EXISTS idx_apk_vault_package_name ON public.apk_vault(package_name);

-- ─────────────────────────────────────────────────────────────────────────────
-- 3. apk_deployment_logs table
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.apk_deployment_logs (
    id           TEXT        PRIMARY KEY,  -- dep-XXXXXX format
    action       TEXT        NOT NULL,
    apk_name     TEXT        NOT NULL,
    devices      INTEGER     NOT NULL DEFAULT 0,
    status       TEXT        NOT NULL,
    performed_by TEXT        NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_apk_deployment_logs_created_at ON public.apk_deployment_logs(created_at DESC);

-- ─────────────────────────────────────────────────────────────────────────────
-- 4. audit_log_archive table
-- ─────────────────────────────────────────────────────────────────────────────
-- original_log_id is TEXT (not UUID) because:
--   - audit_logs.id is UUID (stored as text representation is compatible)
--   - terminal_audit_log.id is UUID (same)
--   - Future TEXT-PK sources may also be archived here
--   TEXT is the safe common denominator; UUID values are stored canonically.
CREATE TABLE IF NOT EXISTS public.audit_log_archive (
    archive_id      UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    original_log_id TEXT        NOT NULL,   -- UUID or TEXT string from source table's id column
    timestamp       TIMESTAMPTZ NOT NULL,
    module          TEXT        NOT NULL,
    action          TEXT        NOT NULL,
    user_email      TEXT        NOT NULL,
    user_name       TEXT        NULL,
    ip_address      TEXT        NULL,
    location        TEXT        NULL,
    target          TEXT        NULL,
    status          TEXT        NOT NULL,
    metadata        JSONB       NOT NULL DEFAULT '{}'::jsonb,
    tenant_id       UUID        NULL,
    tenant_code     VARCHAR(20) NULL,
    source_origin   TEXT        NOT NULL
                    CHECK (source_origin IN ('AUDIT_LOG', 'TERMINAL_AUDIT', 'DEVICE_AUDIT')),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_audit_log_archive_timestamp       ON public.audit_log_archive(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_audit_log_archive_tenant_id       ON public.audit_log_archive(tenant_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_archive_tenant_code     ON public.audit_log_archive(tenant_code);
CREATE INDEX IF NOT EXISTS idx_audit_log_archive_original_log_id ON public.audit_log_archive(original_log_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_archive_source_origin   ON public.audit_log_archive(source_origin);

-- ─────────────────────────────────────────────────────────────────────────────
-- Row Level Security
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE public.complaints        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.apk_vault         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.apk_deployment_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_log_archive ENABLE ROW LEVEL SECURITY;

-- ─────────────────────────────────────────────────────────────────────────────
-- RESTRICTIVE WRITE-BLOCK POLICIES
-- All INSERT, UPDATE, and DELETE operations are blocked for client JWTs.
-- Backend services use supabaseAdmin (service role) which bypasses RLS entirely.
-- ─────────────────────────────────────────────────────────────────────────────

-- complaints: block all client writes
CREATE POLICY "no_client_insert_complaints"
  ON public.complaints AS RESTRICTIVE FOR INSERT
  WITH CHECK (false);

CREATE POLICY "no_client_update_complaints"
  ON public.complaints AS RESTRICTIVE FOR UPDATE
  USING (false);

CREATE POLICY "no_client_delete_complaints"
  ON public.complaints AS RESTRICTIVE FOR DELETE
  USING (false);

-- apk_vault: block all client writes
CREATE POLICY "no_client_insert_apk_vault"
  ON public.apk_vault AS RESTRICTIVE FOR INSERT
  WITH CHECK (false);

CREATE POLICY "no_client_update_apk_vault"
  ON public.apk_vault AS RESTRICTIVE FOR UPDATE
  USING (false);

CREATE POLICY "no_client_delete_apk_vault"
  ON public.apk_vault AS RESTRICTIVE FOR DELETE
  USING (false);

-- apk_deployment_logs: block all client writes
CREATE POLICY "no_client_insert_apk_deploy_logs"
  ON public.apk_deployment_logs AS RESTRICTIVE FOR INSERT
  WITH CHECK (false);

CREATE POLICY "no_client_update_apk_deploy_logs"
  ON public.apk_deployment_logs AS RESTRICTIVE FOR UPDATE
  USING (false);

CREATE POLICY "no_client_delete_apk_deploy_logs"
  ON public.apk_deployment_logs AS RESTRICTIVE FOR DELETE
  USING (false);

-- audit_log_archive: block all client writes
CREATE POLICY "no_client_insert_audit_archive"
  ON public.audit_log_archive AS RESTRICTIVE FOR INSERT
  WITH CHECK (false);

CREATE POLICY "no_client_update_audit_archive"
  ON public.audit_log_archive AS RESTRICTIVE FOR UPDATE
  USING (false);

CREATE POLICY "no_client_delete_audit_archive"
  ON public.audit_log_archive AS RESTRICTIVE FOR DELETE
  USING (false);

-- ─────────────────────────────────────────────────────────────────────────────
-- SELECT POLICIES
--
-- CAST RATIONALE (derived from live schema inspection and p05b/p05c precedent):
--   users.id       is UUID  → auth.uid() is UUID  → no cast needed
--   users.tenant_id is TEXT → UUID columns need ::text cast on both sides
--   Pattern: users.tenant_id::text = <uuid_column>::text
-- ─────────────────────────────────────────────────────────────────────────────

-- complaints: staff (super_admin, internal_staff, admin_ops, support) can read all
CREATE POLICY "staff_read_all_complaints"
  ON public.complaints FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.users
      WHERE users.id = auth.uid()
      AND users.role IN ('super_admin', 'internal_staff', 'admin_ops', 'support')
    )
  );

-- complaints: tenant users can read their own tenant's complaints
-- users.tenant_id is TEXT; complaints.tenant_id is UUID → cast both to text
CREATE POLICY "tenant_user_read_own_complaints"
  ON public.complaints FOR SELECT
  USING (
    tenant_id IS NOT NULL
    AND EXISTS (
      SELECT 1 FROM public.users
      WHERE users.id = auth.uid()
      AND users.tenant_id::text = complaints.tenant_id::text
    )
  );

-- apk_vault: staff only (APK management is internal)
CREATE POLICY "staff_read_apk_vault"
  ON public.apk_vault FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.users
      WHERE users.id = auth.uid()
      AND users.role IN ('super_admin', 'internal_staff', 'admin_ops')
    )
  );

-- apk_deployment_logs: staff only
CREATE POLICY "staff_read_apk_deploy_logs"
  ON public.apk_deployment_logs FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.users
      WHERE users.id = auth.uid()
      AND users.role IN ('super_admin', 'internal_staff', 'admin_ops')
    )
  );

-- audit_log_archive: super_admin and internal_staff can read all
CREATE POLICY "staff_read_all_audit_archive"
  ON public.audit_log_archive FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.users
      WHERE users.id = auth.uid()
      AND users.role IN ('super_admin', 'internal_staff', 'admin_ops')
    )
  );

-- audit_log_archive: tenant admins can read their own tenant's archived logs
-- users.tenant_id is TEXT; audit_log_archive.tenant_id is UUID → cast both to text
CREATE POLICY "tenant_admin_read_own_audit_archive"
  ON public.audit_log_archive FOR SELECT
  USING (
    tenant_id IS NOT NULL
    AND EXISTS (
      SELECT 1 FROM public.users
      WHERE users.id = auth.uid()
      AND users.tenant_id::text = audit_log_archive.tenant_id::text
      AND users.role IN ('owner', 'admin', 'tenant_admin')
    )
  );
