import * as crypto from 'crypto';

export interface OfflineClaimToken {
  agentCode: string;
  onboardingTimestamp: string;
  claimId: string;
  signature: string;
}

export interface OnboardingLineageRecord {
  tenantId: string;
  onboardedByAgent: string;
  onboardingTimestamp: Date;
  onboardingOrigin: string; // e.g., 'ONLINE', 'OFFLINE_SYNC'
  onboardingChannel: string; // e.g., 'MOBILE_APP', 'WEB_PORTAL'
  tenantOrigin: string;
  attributionLineageHash: string; // Immutable hash of the attribution
}

export class ReferralLineageEngine {
  private readonly SECRET_KEY = (() => {
    const key = process.env.AGENT_LINEAGE_SECRET;
    if (!key || key.length < 16) {
      if (process.env.NODE_ENV === 'production' || process.env.BUILD_VARIANT === 'PROD' || process.env.BUILD_VARIANT === 'STAGING') {
        throw new Error('AGENT_LINEAGE_SECRET is required');
      }
      return crypto.randomBytes(32).toString('hex');
    }
    return key;
  })();

  /**
   * Initializes a replay-safe, immutable onboarding attribution record.
   */
  public initializeOnboardingLineage(
    tenantId: string,
    agentCode: string,
    onboardingOrigin: string,
    onboardingChannel: string,
    tenantOrigin: string,
    offlineToken?: OfflineClaimToken
  ): OnboardingLineageRecord {
    
    let timestamp = new Date();
    
    // If onboarding was offline, validate the claim token first
    if (onboardingOrigin === 'OFFLINE_SYNC' && offlineToken) {
      this.validateOfflineClaimToken(offlineToken);
      timestamp = new Date(offlineToken.onboardingTimestamp);
    }

    const lineageHash = this.generateLineageHash(tenantId, agentCode, timestamp.toISOString(), onboardingOrigin);

    const lineageRecord: OnboardingLineageRecord = {
      tenantId,
      onboardedByAgent: agentCode,
      onboardingTimestamp: timestamp,
      onboardingOrigin,
      onboardingChannel,
      tenantOrigin,
      attributionLineageHash: lineageHash,
    };

    // TODO: Persist lineageRecord to database (immutable insert only)
    return lineageRecord;
  }

  /**
   * Validates a signed attribution token generated by an offline agent device.
   */
  public validateOfflineClaimToken(token: OfflineClaimToken): boolean {
    const dataToVerify = `${token.agentCode}:${token.onboardingTimestamp}:${token.claimId}`;
    
    // In a real scenario, this would use a public key mapped to the agent's device
    // or a shared HMAC secret.
    const expectedSignature = crypto
      .createHmac('sha256', this.SECRET_KEY)
      .update(dataToVerify)
      .digest('hex');

    if (token.signature !== expectedSignature) {
      throw new Error('Invalid Offline Claim Token: Signature mismatch or token tampered.');
    }

    // TODO: Verify claimId hasn't been used before to prevent replay attacks
    return true;
  }

  /**
   * Generates an immutable hash to seal the onboarding attribution.
   */
  private generateLineageHash(tenantId: string, agentCode: string, timestamp: string, origin: string): string {
    const data = `${tenantId}|${agentCode}|${timestamp}|${origin}`;
    return crypto.createHash('sha256').update(data).digest('hex');
  }
}
